export interface SpringTopic {
    title: string;
    topics: string[];
}

export class Spring{
    springboot = [
        {
            title: "Controller", topics: [
                "Controller Basics",
                "Spring @Controller",
                "Spring @RestController",
                "Request Mapping",
                "GetMapping",
                "PostMapping",
                "PutMapping",
                "DeleteMapping",
                "PatchMapping",
                "PathVariable",
                "RequestParam",
                "RequestBody",
                "ResponseBody",
                "ResponseEntity",
                "Exception Handling",
                "Controller Advice",
                "Cross-Origin (CORS)",
                "Controller Security",
                "DTO in Controllers",
                "Validation in Controllers",
                "Logging in Controllers",
                "Interceptor in Controllers",
                "Controller Testing",
                "MockMvc Testing",
                "Controller Best Practices",
                "Controller Anti-Patterns"]
        },
        {
            title: "DTO", topics: ["DTO Basics",
                "DTO vs Entity",
                "DTO in MVC",
                "DTO in Spring Boot",
                "Lombok with DTO",
                "Mapping DTOs",
                "ModelMapper",
                "MapStruct",
                "Jackson and DTO",
                "Serialization",
                "Deserialization",
                "Nested DTOs",
                "DTO Validation",
                "Custom Validators",
                "DTO in REST APIs",
                "DTO in Microservices",
                "DTO in GraphQL",
                "DTO in Kafka/RabbitMQ",
                "DTO in Security",
                "DTO Performance",
                "DTO Best Practices",
                "Testing DTOs",
                "DTO Anti-Patterns"]
        },
        {
            title: "Service", topics: ["Service Layer Basics",
                "MVC & Service Layer",
                "Service Layer in Spring Boot",
                "@Service Annotation",
                "Dependency Injection",
                "Service vs Repository",
                "Database Interaction",
                "DTO in Service Layer",
                "Exception Handling",
                "Transaction Management",
                "Best Practices",
                "Business Logic",
                "Unit Testing",
                "Logging",
                "Integration Testing",
                "Security",
                "Caching",
                "External API Calls",
                "Feign Client",
                "Asynchronous Processing",
                "Event-Driven Communication",
                "Microservices Communication",
                "Large Data Handling",
                "Performance Optimization",
                "Anti-Patterns"]
        },
        {
            title: "JPA", topics: [
                "JPA Basics",
                "Entity Mapping",
                "Entity Lifecycle",
                "Primary Keys & Generation Strategies",
                "JPA Annotations (@Entity, @Table, @Id, @Column)",
                "Relationships (OneToOne, OneToMany, ManyToOne, ManyToMany)",
                "JPQL (Java Persistence Query Language)",
                "Criteria API",
                "Native SQL Queries",
                "Named Queries",
                "Transaction Management",
                "Lazy vs Eager Loading",
                "Caching (First-Level & Second-Level)",
                "JPA with Spring Data",
                "Repository Pattern",
                "Spring Data JPA Repositories",
                "Paging & Sorting",
                "JPA Performance Optimization",
                "Auditing in JPA (Envers)",
                "JPA Query Optimization",
                "JPA Best Practices",
                "Testing JPA with Spring"]
        },
        {
            title: "Hibernate", topics: [
                "Hibernate Basics",
                "Hibernate vs JDBC",
                "Architecture & Workflow",
                "Configuration",
                "SessionFactory & Session",
                "Entity Lifecycle",
                "Annotations",
                "Primary Key Strategies",
                "Entity Mapping",
                "HQL & Criteria API",
                "Native SQL Queries",
                "Named Queries",
                "Pagination",
                "Caching",
                "Lazy vs Eager Loading",
                "Transaction Management",
                "Locking Strategies",
                "Fetching Strategies",
                "Interceptors & Listeners",
                "Inheritance Mapping",
                "Hibernate with Spring Boot",
                "Hibernate & JPA",
                "Spring Data JPA vs Hibernate",
                "Audit Logging",
                "Performance Optimization",
                "Testing",
                "Common Issues & Debugging"
              ]
        },
        {
            title: "Application Properties", topics: [
                "Application Properties Basics",
                "Spring Boot Properties",
                "Common Properties",
                "YAML vs Properties",
                "Spring Profiles",
                "Custom Properties",
                "Externalized Configuration",
                "Binding to POJOs",
                "@Value Annotation",
                "Configuration Prefixes",
                "Property Sources",
                "Configuration Property Types",
                "Profile-Specific Config",
                "Profiles in application.yml",
                "Placeholder Resolution",
                "Property Encryption",
                "Spring Cloud Config",
                "Config Server",
                "Environment Variables",
                "Multiple Property Files",
                "Property Best Practices"
            ]
        },
        {
            title: "Annotations", topics: [
                "@SpringBootApplication",
                "@RestController",
                "@Controller",
                "@Service",
                "@Repository",
                "@Component",
                "@Bean",
                "@Configuration",
                "@ComponentScan",
                "@Autowired",
                "@Value",
                "@Qualifier",
                "@Primary",
                "@Lazy",
                "@Scope",
                "@RequestMapping",
                "@GetMapping",
                "@PostMapping",
                "@PutMapping",
                "@DeleteMapping",
                "@PatchMapping",
                "@RequestParam",
                "@PathVariable",
                "@RequestBody",
                "@ResponseBody",
                "@ResponseStatus",
                "@CrossOrigin",
                "@ExceptionHandler",
                "@RestControllerAdvice",
                "@Transactional",
                "@EnableScheduling",
                "@Scheduled",
                "@EnableAsync",
                "@Async",
                "@Cacheable",
                "@CachePut",
                "@CacheEvict",
                "@EnableCaching",
                "@Entity",
                "@Table",
                "@Id",
                "@GeneratedValue",
                "@Column",
                "@OneToOne",
                "@OneToMany",
                "@ManyToOne",
                "@ManyToMany",
                "@JoinColumn",
                "@JoinTable",
                "@EnableJpaRepositories",
                "@Modifying",
                "@Query",
                "@RestTemplate",
                "@FeignClient",
                "@EnableFeignClients",
                "@EnableEurekaClient",
                "@EnableCircuitBreaker",
                "@Retryable",
                "@Recover"]
        },
        {
            title: "Security", topics:[
                "Security Fundamentals",
                "Authentication & Authorization",
                "Security Configuration",
                "UserDetailsService & Encoding",
                "Security Filters & Context",
                "RBAC",
                "Method-Level Security",
                "JWT Authentication",
                "OAuth2 & OpenID Connect",
                "OAuth2 Authorization Server",
                "OAuth2 Resource Server",
                "Session Management & CSRF",
                "CORS Handling",
                "Database Authentication",
                "Form & Basic Authentication",
                "LDAP Authentication",
                "Two-Factor Authentication",
                "Security for Microservices",
                "API Gateway Security",
                "Testing & Debugging"
              ]
        },
        {
            title: "MicroServices", topics:[
                "Spring Boot Actuator",
                "Spring Cloud Config",
                "Eureka (Service Discovery)",
                "Load Balancer",
                "Spring Cloud Gateway",
                "OpenFeign",
                "Resilience4j (Circuit Breaker)",
                "Sleuth & Zipkin (Tracing)",
                "Spring Cloud Bus",
                "Spring Security & OAuth2",
                "Kafka/RabbitMQ (Event-Driven)",
                "Microservices Data Management",
                "Docker & Kubernetes",
                "API Gateway & Rate Limiting",
                "Logging & Monitoring",
                "Testing Strategies",
                "DevOps & CI/CD",
                "Scaling & Performance"
              ]
        },
        {
            title: "Dependency injections", topics: ["DI Basics",
                "Types of DI (Constructor, Setter, Field)",
                "Inversion of Control (IoC)",
                "Spring DI Annotations (@Autowired, @Inject)",
                "Bean Configuration (XML, Java-based, Annotations)",
                "Bean Scopes (Singleton, Prototype)",
                "DI and Loose Coupling",
                "DI in Spring Framework",
                "Autowiring Modes (ByType, ByName)",
                "DI with Qualifiers (@Qualifier)",
                "DI in Spring Boot",
                "Circular Dependencies",
                "Constructor Injection",
                "Setter Injection",
                "Field Injection",
                "DI with Profiles",
                "DI and Lifecycle of Beans",
                "Spring Bean Post-Processors",
                "Testing DI",
                "DI Best Practices"]
        },
        {
            title: "ORM", topics: ["ORM Basics",
                "JPA vs Hibernate",
                "Entity Mapping",
                "ORM Frameworks",
                "Primary Key Generation",
                "Lazy vs Eager Loading",
                "Relationships (OneToOne, OneToMany, ManyToOne, ManyToMany)",
                "JPQL (Java Persistence Query Language)",
                "Criteria API",
                "Native Queries",
                "Named Queries",
                "ORM Caching",
                "Transaction Management",
                "Query Optimization",
                "Inheritance Mapping",
                "Entity Lifecycle",
                "Fetching Strategies",
                "ORM with Spring Data",
                "ORM with Spring Boot",
                "Spring Data JPA",
                "Testing ORM",
                "Performance Tuning in ORM"]
        },
        {
            title: "Entity", topics: ["Entity Basics",
                "Entity Mapping",
                "Primary Key Generation",
                "Entity Annotations (@Entity, @Table, @Id, @Column)",
                "Relationships (OneToOne, OneToMany, ManyToOne, ManyToMany)",
                "Entity Lifecycle",
                "DTO vs Entity",
                "JPA vs Hibernate Entities",
                "Lazy vs Eager Loading",
                "Cascade Operations",
                "Entity Validation",
                "Versioning (Optimistic Locking)",
                "Inheritance Mapping",
                "Composite Keys",
                "Entity Manager",
                "Fetching Strategies",
                "Entity Auditing",
                "Entity Performance Optimization",
                "Entity Listeners",
                "Testing Entities",
                "Entity Best Practices"]
        },
        {
            title: "Validation", topics: [
                "Validation Basics",
                "Bean Validation (JSR 303/380)",
                "Validation Annotations (@NotNull, @Size, @Email, etc.)",
                "Custom Validation Annotations",
                "Group Validation",
                "Validation in Spring Boot",
                "Validator Interface",
                "ConstraintValidator",
                "Message Interpolation",
                "Cross-field Validation",
                "Validation with DTOs",
                "Validation in REST APIs",
                "Global Validation (@Valid, @Validated)",
                "Custom Error Messages",
                "Validation on Method Parameters",
                "Hibernate Validator",
                "Validation in Spring Security",
                "Validation in Microservices",
                "Validation Best Practices"]
        },
        {
            title: "Caching", topics: [
                "Caching Basics",
                "Cache Annotations (@Cacheable, @CacheEvict, @CachePut)",
                "Cache Managers",
                "Cache Providers (EhCache, Redis, etc.)",
                "Spring Cache Abstraction",
                "Caching Strategies",
                "Cache Configurations",
                "Cache Key Generation",
                "Cache Eviction Strategies",
                "Cache TTL (Time to Live)",
                "Cache Synchronization",
                "Distributed Caching",
                "Caching in Microservices",
                "Cache & Performance Optimization",
                "Cache Monitoring",
                "Caching with Spring Boot",
                "Cache Best Practices",
                "Testing Caching",
                "Conditional Caching",
                "Cache & Security"]
        },
        {
            title: "Transaction", topics: ["Transaction Basics",
                "ACID Properties",
                "Transaction Management in Spring",
                "Declarative Transactions (@Transactional)",
                "Programmatic Transactions",
                "Propagation Types (REQUIRED, REQUIRES_NEW, etc.)",
                "Isolation Levels",
                "Transaction Rollback",
                "Transaction Timeout",
                "Transaction Management in Microservices",
                "Nested Transactions",
                "Transaction in Spring Boot",
                "Database Transaction Support (JPA, JDBC)",
                "Transaction in Distributed Systems",
                "Transaction Best Practices",
                "Transaction Error Handling",
                "Transaction with Multiple Data Sources",
                "Testing Transactions",
                "Event-Driven Transactions",
                "Optimistic vs Pessimistic Locking"]
        },
        {
            title: "Messaging", topics: ["Messaging Basics",
                "Message Queues (RabbitMQ, ActiveMQ)",
                "Publish-Subscribe Pattern",
                "Message Brokers",
                "JMS (Java Message Service)",
                "Spring JMS Integration",
                "Message Producers & Consumers",
                "Spring Integration for Messaging",
                "Message Listeners",
                "Message Conversion",
                "Asynchronous Messaging",
                "Transactional Messaging",
                "Message Acknowledgement",
                "Messaging with Kafka",
                "Spring Cloud Stream",
                "Message-Driven POJOs (MDP)",
                "Message Filtering & Routing",
                "Message Priority",
                "Message Persistence",
                "Error Handling in Messaging",
                "Message Security",
                "Testing Messaging Systems"]
        },
        {
            title: "Testing", topics: ["Testing Basics",
                "Unit Testing",
                "Integration Testing",
                "End-to-End Testing",
                "Test-Driven Development (TDD)",
                "Mockito",
                "JUnit",
                "Spring Testing (@SpringBootTest, @WebMvcTest)",
                "MockMvc",
                "Testing Repositories",
                "Testing Services",
                "Testing Controllers",
                "Test Configuration & Profiles",
                "Testing with TestContainers",
                "Parameterized Tests",
                "Testing Asynchronous Code",
                "Testing REST APIs",
                "Contract Testing",
                "Mocking External Services",
                "Test Coverage",
                "Performance Testing",
                "CI/CD & Testing",
                "Test Best Practices"]
        },
        {title: "AOP", topics: ["AOP"]},
        {title: "Logging", topics: ["Logging"]},
        {title: "RestTemplate", topics: ["RestTemplate"]},
        {title: "WebSocket", topics: ["WebSocket"]},
        {title: "Scheduler", topics: ["Scheduler"]},
        {title: "Monitoring", topics: ["Monitoring"]},
        {title: "Deployment", topics: ["Deployment"]},
        {title: "CI/CD", topics: ["CI/CD"]},

    ];
}